substitutions:
  _REPO_PATH_PREFIX: "us-east1-docker.pkg.dev/warm-capsule-470118-i5/cicd-artifact-repo/bishopllc-storefront-app"
  _ATTESTOR: "itsec-approver"
  _ATTESTOR_PROJECT: "warm-capsule-470118-i5"
  _KEY_LOCATION: "us-east1"
  _KEYRING: "binauthz-keys"
  _KEY: "itsec-approver"
  _KEY_VERSION: "1"

options: { logging: CLOUD_LOGGING_ONLY }

# Optional: two-person rule before signing
approvals:
- approvers:
  - maxbishop.work.gcp@gmail.com      # Only Security can approve

steps:

# first step (grab IMAGE from PubSub)
- id: "extract image@digest from images.built event"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      echo "$BUILD_TRIGGER_MESSAGE" | tee /workspace/event.json
      IMAGE=$(jq -r '.image // empty' /workspace/event.json)
      [[ -n "$IMAGE" ]] || { echo "Event missing .image"; cat /workspace/event.json; exit 2; }
      echo "IMAGE=$IMAGE" | tee /workspace/approved.txt


- id: "sign-and-create (after Security approval)"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  waitFor: ["-"]
  entrypoint: bash
  args:
    - -ceu
    - |
      source /workspace/approved.txt
      gcloud beta container binauthz attestations sign-and-create \
        --artifact-url="$IMAGE" \
        --attestor="$_ATTESTOR" \
        --attestor-project="$_ATTESTOR_PROJECT" \
        --keyversion-project="$PROJECT_ID" \
        --keyversion-location="$_KEY_LOCATION" \
        --keyversion-keyring="$_KEYRING" \
        --keyversion-key="$_KEY" \
        --keyversion="$_KEY_VERSION" \
        --format=json

- id: "publish images.approved"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      source /workspace/approved.txt
      gcloud pubsub topics publish images.approved \
        --message="{\"image\":\"${IMAGE}\",\"attestor\":\"${_ATTESTOR}\",\"project\":\"${_ATTESTOR_PROJECT}\"}"


- id: "list attestation (audit)"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      source /workspace/approved.txt
      gcloud container binauthz attestations list \
        --artifact-url="$IMAGE" \
        --attestor="$_ATTESTOR" \
        --attestor-project="$_ATTESTOR_PROJECT" \
        --format="table(CREATE_TIME,RESOURCE_URI,PROJECT_ID)"
