# Cloud Build: Security approval to sign an image digest and create a Binary Authorization attestation

substitutions:
  # Required inputs when running the trigger:
  _IMAGE: "us-east1-docker.pkg.dev/warm-capsule-470118-i5/cicd-artifact-repo/bishopllc-storefront-app@sha256:4bebcd56ffeb3ee494ee19ea8e05b90aefb0084b0a157e028b598e1436df65f8"           # full image *with* digest, e.g. us-east1-docker.pkg.dev/PROJECT/REPO/IMAGE@sha256:...
  _ATTESTOR: "itsec-approvers"        # attestor resource, e.g. itsec-approver
  _ATTESTOR_PROJECT: "warm-capsule-470118-i5" # attestor project i.e. warm-capsule-470118-i5
  _KEY_LOCATION: "us-east1"
  _KEYRING: "binauthz-keys"
  _KEY: "itsec-approver"
  _KEY_VERSION: "1"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Sanity check inputs
  - id: "validate inputs"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        [[ -n "$_IMAGE" && "$_IMAGE" == *"@sha256:"* ]] || { echo "ERROR: _IMAGE must include @sha256:..."; exit 2; }
        [[ -n "$_ATTESTOR" ]] || { echo "ERROR: _ATTESTOR is required"; exit 2; }

  # 2) Sign + create attestation with the IT-Sec KMS key
    - id: "sign and create attestation (idempotent)"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        set +e
        OUT=$(
          gcloud beta container binauthz attestations sign-and-create \
            --artifact-url="$_IMAGE" \
            --attestor="$_ATTESTOR" \
            --attestor-project="$_ATTESTOR_PROJECT" \
            --keyversion-project="$PROJECT_ID" \
            --keyversion-location="$_KEY_LOCATION" \
            --keyversion-keyring="$_KEYRING" \
            --keyversion-key="$_KEY" \
            --keyversion="$_KEY_VERSION" \
            --format="json" 2>&1
        )
        STATUS=$?
        set -e

        if [[ $STATUS -ne 0 ]]; then
          if grep -qi "subject of a conflict" <<< "$OUT"; then
            echo "Attestation already exists; continuing."
          else
            echo "$OUT"
            exit $STATUS
          fi
        fi


  # 3) List the attestation we just created (for audit visibility in logs)
  - id: "list attestation"
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -ceu
      - |
        gcloud container binauthz attestations list \
          --artifact-url="$_IMAGE" \
          --attestor="$_ATTESTOR" \
          --format="table(CREATE_TIME,RESOURCE_URI,PROJECT_ID)"
