substitutions:
  _REPO_PATH_PREFIX: "us-east1-docker.pkg.dev/warm-capsule-470118-i5/cicd-artifact-repo/bishopllc-storefront-app"
  _ATTESTOR: "itsec-approver"
  _ATTESTOR_PROJECT: "warm-capsule-470118-i5"
  _KEY_LOCATION: "us-east1"
  _KEYRING: "binauthz-keys"
  _KEY: "itsec-approver"
  _KEY_VERSION: "1"

options: { logging: CLOUD_LOGGING_ONLY }

# Optional: two-person rule before signing
approvals:
- approvers:
  - maxbishop.work.gcp@gmail.com      # Only Security can approve

steps:
- id: "extract image@digest from event"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      # Cloud Build injects the Pub/Sub payload into $BUILD_TRIGGER_MESSAGE
      # Artifact Registry publish event payload has fields like "tag", "version", "package", and "registry"
      # For container images, you’ll get the full *version* which includes the digest.
      echo "$BUILD_TRIGGER_MESSAGE" | tee /workspace/event.json

      # Try to pull out an image URI with digest; adjust jq paths if your payload differs
      IMAGE=$(
        jq -r '
          .version | select(test("@sha256:")) // empty
        ' /workspace/event.json
      )

      # If the payload only has repo+tag, resolve to digest:
      if [[ -z "$IMAGE" ]]; then
        PKG=$(jq -r '.package' /workspace/event.json)   # e.g. projects/.../locations/.../repositories/.../packages/...
        TAG=$(jq -r '.tag // empty' /workspace/event.json)
        if [[ -n "$TAG" && "$TAG" != "null" ]]; then
          REF="$_REPO_PATH_PREFIX:$TAG"
          DIGEST=$(gcloud artifacts docker images describe "$REF" --format='get(image_summary.digest)')
          IMAGE="$_REPO_PATH_PREFIX@$DIGEST"
        fi
      fi

      [[ -n "$IMAGE" ]] || { echo "Could not determine image@digest from event"; exit 2; }
      echo "IMAGE=$IMAGE" | tee /workspace/approved.txt

- id: "sign-and-create (after Security approval)"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  waitFor: ["-"]
  entrypoint: bash
  args:
    - -ceu
    - |
      source /workspace/approved.txt
      gcloud beta container binauthz attestations sign-and-create \
        --artifact-url="$IMAGE" \
        --attestor="$_ATTESTOR" \
        --attestor-project="$_ATTESTOR_PROJECT" \
        --keyversion-project="$PROJECT_ID" \
        --keyversion-location="$_KEY_LOCATION" \
        --keyversion-keyring="$_KEYRING" \
        --keyversion-key="$_KEY" \
        --keyversion="$_KEY_VERSION" \
        --format=json

- id: "list attestation (audit)"
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -ceu
    - |
      source /workspace/approved.txt
      gcloud container binauthz attestations list \
        --artifact-url="$IMAGE" \
        --attestor="$_ATTESTOR" \
        --attestor-project="$_ATTESTOR_PROJECT" \
        --format="table(CREATE_TIME,RESOURCE_URI,PROJECT_ID)"
